---
- name: ScaleFT yum repo is installed
  yum_repository:
    name: scaleft
    description: ScaleFT YUM repo
    baseurl: https://pkg.scaleft.com/scaleft_yum.repo
    gpgkey: https://dist.scaleft.com/pki/scaleft_rpm_key.asc

- name: ScaleFT Server Agent is installed
  yum:
    name:
    - scaleft-server-tools
    state: present
